In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime 

from pandas.plotting import scatter_matrix
import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/matteeussPei/Hotel-Booking-Demand/main/hotel_bookings.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
print('Total de variáveis:', df.shape[1])
print('Total de entradas:', df.shape[0])

Total de variáveis: 32
Total de entradas: 119390

In [4]:
df['is_canceled'].mean()

0.37041628277075134

In [5]:
pd.DataFrame({'tipo de dados':df.dtypes,
                'dados_ausentes(%)': (df.isnull().sum()/df.shape[0])*100,
                    'valores unicos': df.nunique()}).sort_values(by='dados_ausentes(%)', ascending=False)

,tipo de dados,dados_ausentes(%),valores unicos
company,float64,94.306893,352
agent,float64,13.686238,333
country,object,0.408744,177
children,float64,0.003350,5
reserved_room_type,object,0.000000,10
assigned_room_type,object,0.000000,12
booking_changes,int64,0.000000,21
deposit_type,object,0.000000,3
hotel,object,0.000000,2
previous_cancellations,int64,0.000000,15
days_in_waiting_list,int64,0.000000,128
customer_type,object,0.000000,4
adr,float64,0.000000,8879
required_car_parking_spaces,int64,0.000000,5
total_of_special_requests,int64,0.000000,6
reservation_status,object,0.000000,3
previous_bookings_not_canceled,int64,0.000000,73
is_repeated_guest,int64,0.000000,2
is_canceled,int64,0.000000,2
distribution_channel,object,0.000000,5
market_segment,object,0.000000,8
meal,object,0.000000,5
babies,int64,0.000000,5
adults,int64,0.000000,14
stays_in_week_nights,int64,0.000000,35
stays_in_weekend_nights,int64,0.000000,17
arrival_date_day_of_month,int64,0.000000,31
arrival_date_week_number,int64,0.000000,53
arrival_date_month,object,0.000000,12
arrival_date_year,int64,0.000000,3
lead_time,int64,0.000000,479
reservation_status_date,object,0.000000,926

In [6]:
df.drop(columns = ['agent', 'company'], inplace=True)

In [7]:
pd.DataFrame({'tipo de dados':df.dtypes,
                'dados_ausentes(%)': (df.isnull().sum()/df.shape[0])*100,
                    'valores unicos': df.nunique()}).sort_values(by='dados_ausentes(%)', ascending=False)

,tipo de dados,dados_ausentes(%),valores unicos
country,object,0.408744,177
children,float64,0.003350,5
hotel,object,0.000000,2
is_repeated_guest,int64,0.000000,2
reservation_status,object,0.000000,3
total_of_special_requests,int64,0.000000,6
required_car_parking_spaces,int64,0.000000,5
adr,float64,0.000000,8879
customer_type,object,0.000000,4
days_in_waiting_list,int64,0.000000,128
deposit_type,object,0.000000,3
booking_changes,int64,0.000000,21
assigned_room_type,object,0.000000,12
reserved_room_type,object,0.000000,10
previous_bookings_not_canceled,int64,0.000000,73
previous_cancellations,int64,0.000000,15
distribution_channel,object,0.000000,5
is_canceled,int64,0.000000,2
market_segment,object,0.000000,8
meal,object,0.000000,5
babies,int64,0.000000,5
adults,int64,0.000000,14
stays_in_week_nights,int64,0.000000,35
stays_in_weekend_nights,int64,0.000000,17
arrival_date_day_of_month,int64,0.000000,31
arrival_date_week_number,int64,0.000000,53
arrival_date_month,object,0.000000,12
arrival_date_year,int64,0.000000,3
lead_time,int64,0.000000,479
reservation_status_date,object,0.000000,926

In [8]:
df.drop(columns=['country', 'arrival_date_year', 'reservation_status', 'arrival_date_month'], inplace = True)

In [9]:
df = df.dropna(subset = ['children']).reset_index(drop=True)

In [10]:
filtro = (df['babies'] == 0) & (df['children'] == 0) & (df['adults'] == 0)
df = df[~filtro]

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,Resort Hotel,0,342,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015-07-01
1,Resort Hotel,0,737,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015-07-01
2,Resort Hotel,0,7,27,1,0,1,1,0.0,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
3,Resort Hotel,0,13,27,1,0,1,1,0.0,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
4,Resort Hotel,0,14,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015-07-03

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85427 entries, 0 to 119385
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85427 non-null  object
 1   is_canceled                     85427 non-null  int64
 2   lead_time                       85427 non-null  int64
 3   arrival_date_week_number        85427 non-null  int64
 4   arrival_date_day_of_month       85427 non-null  int64
 5   stays_in_weekend_nights         85427 non-null  int64
 6   stays_in_week_nights            85427 non-null  int64
 7   adults                          85427 non-null  int64
 8   children                        85427 non-null  float64
 9   babies                          85427 non-null  int64
 10  meal                            85427 non-null  object
 11  market_segment                  85427 non-null  object
 12  distribution_channel            85427 non-null  object
 13  is_repeated_guest               85427 non-null  int64
 14  previous_cancellations          85427 non-null  int64
 15  previous_bookings_not_canceled  85427 non-null  int64
 16  reserved_room_type              85427 non-null  object
 17  assigned_room_type              85427 non-null  object
 18  booking_changes                 85427 non-null  int64
 19  deposit_type                    85427 non-null  object
 20  days_in_waiting_list            85427 non-null  int64
 21  customer_type                   85427 non-null  object
 22  adr                             85427 non-null  float64
 23  required_car_parking_spaces     85427 non-null  int64
 24  total_of_special_requests       85427 non-null  int64
 25  reservation_status_date         85427 non-null  object
dtypes: float64(2), int64(15), object(9)
memory usage: 17.6+ MB

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85427 entries, 0 to 119385
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85427 non-null  object
 1   is_canceled                     85427 non-null  int64
 2   lead_time                       85427 non-null  int64
 3   arrival_date_week_number        85427 non-null  int64
 4   arrival_date_day_of_month       85427 non-null  int64
 5   stays_in_weekend_nights         85427 non-null  int64
 6   stays_in_week_nights            85427 non-null  int64
 7   adults                          85427 non-null  int64
 8   children                        85427 non-null  float64
 9   babies                          85427 non-null  int64
 10  meal                            85427 non-null  object
 11  market_segment                  85427 non-null  object
 12  distribution_channel            85427 non-null  object
 13  is_repeated_guest               85427 non-null  int64
 14  previous_cancellations          85427 non-null  int64
 15  previous_bookings_not_canceled  85427 non-null  int64
 16  reserved_room_type              85427 non-null  object
 17  assigned_room_type              85427 non-null  object
 18  booking_changes                 85427 non-null  int64
 19  deposit_type                    85427 non-null  object
 20  days_in_waiting_list            85427 non-null  int64
 21  customer_type                   85427 non-null  object
 22  adr                             85427 non-null  float64
 23  required_car_parking_spaces     85427 non-null  int64
 24  total_of_special_requests       85427 non-null  int64
 25  reservation_status_date         85427 non-null  object
dtypes: float64(2), int64(15), object(9)
memory usage: 17.6+ MB

In [15]:
df['children'] = df['children'].astype('int64', errors='raise')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85427 entries, 0 to 119385
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85427 non-null  object
 1   is_canceled                     85427 non-null  int64
 2   lead_time                       85427 non-null  int64
 3   arrival_date_week_number        85427 non-null  int64
 4   arrival_date_day_of_month       85427 non-null  int64
 5   stays_in_weekend_nights         85427 non-null  int64
 6   stays_in_week_nights            85427 non-null  int64
 7   adults                          85427 non-null  int64
 8   children                        85427 non-null  int64
 9   babies                          85427 non-null  int64
 10  meal                            85427 non-null  object
 11  market_segment                  85427 non-null  object
 12  distribution_channel            85427 non-null  object
 13  is_repeated_guest               85427 non-null  int64
 14  previous_cancellations          85427 non-null  int64
 15  previous_bookings_not_canceled  85427 non-null  int64
 16  reserved_room_type              85427 non-null  object
 17  assigned_room_type              85427 non-null  object
 18  booking_changes                 85427 non-null  int64
 19  deposit_type                    85427 non-null  object
 20  days_in_waiting_list            85427 non-null  int64
 21  customer_type                   85427 non-null  object
 22  adr                             85427 non-null  float64
 23  required_car_parking_spaces     85427 non-null  int64
 24  total_of_special_requests       85427 non-null  int64
 25  reservation_status_date         85427 non-null  object
dtypes: float64(1), int64(16), object(9)
memory usage: 17.6+ MB

In [17]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,Resort Hotel,0,342,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015-07-01
1,Resort Hotel,0,737,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015-07-01
2,Resort Hotel,0,7,27,1,0,1,1,0,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
3,Resort Hotel,0,13,27,1,0,1,1,0,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
4,Resort Hotel,0,14,27,1,0,2,2,0,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015-07-03

In [18]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

df['year'] = df['reservation_status_date'].dt.year
df['month'] = df['reservation_status_date'].dt.month
df['day'] = df['reservation_status_date'].dt.day
df.drop(columns=['reservation_status_date'], inplace=True)

In [19]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,year,month,day
0,Resort Hotel,0,342,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015,7,1
1,Resort Hotel,0,737,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015,7,1
2,Resort Hotel,0,7,27,1,0,1,1,0,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015,7,2
3,Resort Hotel,0,13,27,1,0,1,1,0,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015,7,2
4,Resort Hotel,0,14,27,1,0,2,2,0,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015,7,3

In [20]:
from sklearn import preprocessing

In [21]:
cat_cols = [col for col in df.columns if df[col].dtype == 'O']

In [22]:
cat_cols.append('year')

In [23]:
cat_cols

['hotel',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'year']

In [24]:
cat_cols.append('is_canceled')
cat_cols.append('month')
cat_cols.append('day')
cat_cols.append('is_repeated_guest')

In [25]:
cat_cols

['hotel',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'year',
 'is_canceled',
 'month',
 'day',
 'is_repeated_guest']

In [26]:
cat_var = df[cat_cols]
cat_var.head()

,hotel,meal,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,year,is_canceled,month,day,is_repeated_guest
0,Resort Hotel,BB,Direct,Direct,C,C,No Deposit,Transient,2015,0,7,1,0
1,Resort Hotel,BB,Direct,Direct,C,C,No Deposit,Transient,2015,0,7,1,0
2,Resort Hotel,BB,Direct,Direct,A,C,No Deposit,Transient,2015,0,7,2,0
3,Resort Hotel,BB,Corporate,Corporate,A,A,No Deposit,Transient,2015,0,7,2,0
4,Resort Hotel,BB,Online TA,TA/TO,A,A,No Deposit,Transient,2015,0,7,3,0

In [27]:
le = preprocessing.LabelEncoder()

In [28]:
df[cat_cols] = df[cat_cols].apply(le.fit_transform)

In [29]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,year,month,day
0,1,0,342,27,1,0,0,2,0,0,0,3,1,0,0,0,2,2,3,0,0,2,0.0,0,0,1,6,0
1,1,0,737,27,1,0,0,2,0,0,0,3,1,0,0,0,2,2,4,0,0,2,0.0,0,0,1,6,0
2,1,0,7,27,1,0,1,1,0,0,0,3,1,0,0,0,0,2,0,0,0,2,75.0,0,0,1,6,1
3,1,0,13,27,1,0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,2,75.0,0,0,1,6,1
4,1,0,14,27,1,0,2,2,0,0,0,6,3,0,0,0,0,0,0,0,0,2,98.0,0,1,1,6,2

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85427 entries, 0 to 119385
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85427 non-null  int64
 1   is_canceled                     85427 non-null  int64
 2   lead_time                       85427 non-null  int64
 3   arrival_date_week_number        85427 non-null  int64
 4   arrival_date_day_of_month       85427 non-null  int64
 5   stays_in_weekend_nights         85427 non-null  int64
 6   stays_in_week_nights            85427 non-null  int64
 7   adults                          85427 non-null  int64
 8   children                        85427 non-null  int64
 9   babies                          85427 non-null  int64
 10  meal                            85427 non-null  int64
 11  market_segment                  85427 non-null  int64
 12  distribution_channel            85427 non-null  int64
 13  is_repeated_guest               85427 non-null  int64
 14  previous_cancellations          85427 non-null  int64
 15  previous_bookings_not_canceled  85427 non-null  int64
 16  reserved_room_type              85427 non-null  int64
 17  assigned_room_type              85427 non-null  int64
 18  booking_changes                 85427 non-null  int64
 19  deposit_type                    85427 non-null  int64
 20  days_in_waiting_list            85427 non-null  int64
 21  customer_type                   85427 non-null  int64
 22  adr                             85427 non-null  float64
 23  required_car_parking_spaces     85427 non-null  int64
 24  total_of_special_requests       85427 non-null  int64
 25  year                            85427 non-null  int64
 26  month                           85427 non-null  int64
 27  day                             85427 non-null  int64
dtypes: float64(1), int64(27)
memory usage: 18.9 MB

## StandartScale

In [31]:
df.var()

hotel                                0.238554
is_canceled                          0.201918
lead_time                         7313.020113
arrival_date_week_number           186.616969
arrival_date_day_of_month           78.158589
stays_in_weekend_nights              1.060883
stays_in_week_nights                 4.197863
adults                               0.386915
children                             0.211678
babies                               0.013164
meal                                 1.171499
market_segment                       1.804945
distribution_channel                 0.884936
is_repeated_guest                    0.037774
previous_cancellations               0.139275
previous_bookings_not_canceled       3.066050
reserved_room_type                   3.394844
assigned_room_type                   3.921137
booking_changes                      0.508052
deposit_type                         0.016151
days_in_waiting_list                92.179692
customer_type                        0.272797
adr                               3045.367104
required_car_parking_spaces          0.080688
total_of_special_requests            0.695074
year                                 0.461891
month                               10.440251
day                                 77.339793
dtype: float64

In [32]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,year,month,day
0,1,0,342,27,1,0,0,2,0,0,0,3,1,0,0,0,2,2,3,0,0,2,0.0,0,0,1,6,0
1,1,0,737,27,1,0,0,2,0,0,0,3,1,0,0,0,2,2,4,0,0,2,0.0,0,0,1,6,0
2,1,0,7,27,1,0,1,1,0,0,0,3,1,0,0,0,0,2,0,0,0,2,75.0,0,0,1,6,1
3,1,0,13,27,1,0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,2,75.0,0,0,1,6,1
4,1,0,14,27,1,0,2,2,0,0,0,6,3,0,0,0,0,0,0,0,0,2,98.0,0,1,1,6,2

In [33]:
cat_var = df[cat_cols]
cat_var.head()

,hotel,meal,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,year,is_canceled,month,day,is_repeated_guest
0,1,0,3,1,2,2,0,2,1,0,6,0,0
1,1,0,3,1,2,2,0,2,1,0,6,0,0
2,1,0,3,1,0,2,0,2,1,0,6,1,0
3,1,0,2,0,0,0,0,2,1,0,6,1,0
4,1,0,6,3,0,0,0,2,1,0,6,2,0

In [34]:
num_cols = df.drop(columns=cat_cols)
num_cols.head()

,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,342,27,1,0,0,2,0,0,0,0,3,0,0.0,0,0
1,737,27,1,0,0,2,0,0,0,0,4,0,0.0,0,0
2,7,27,1,0,1,1,0,0,0,0,0,0,75.0,0,0
3,13,27,1,0,1,1,0,0,0,0,0,0,75.0,0,0
4,14,27,1,0,2,2,0,0,0,0,0,0,98.0,0,1

In [35]:
#num_cols['arrival_date_day_of_month'] =

In [36]:
from sklearn.preprocessing import StandardScaler
sca = StandardScaler()
X_temp= sca.fit_transform(num_cols)
X_temp = pd.DataFrame(X_temp, columns= num_cols.columns)

In [37]:
X_temp.head()

,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,3.069363,0.013153,-1.67532,-0.979707,-1.285557,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,3.833545,-0.071077,-1.935646,-0.302358,-0.844568
1,7.688398,0.013153,-1.67532,-0.979707,-1.285557,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,5.236515,-0.071077,-1.935646,-0.302358,-0.844568
2,-0.848046,0.013153,-1.67532,-0.979707,-0.797480,-1.423798,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.576569,-0.302358,-0.844568
3,-0.777884,0.013153,-1.67532,-0.979707,-0.797480,-1.423798,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.576569,-0.302358,-0.844568
4,-0.766190,0.013153,-1.67532,-0.979707,-0.309402,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.159785,-0.302358,0.354895

In [38]:
frames = [cat_var, X_temp]

In [39]:
df = pd.concat([cat_var.reset_index(drop=True), X_temp.reset_index(drop=True)], axis = 1)

In [40]:
df.head()

,hotel,meal,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,year,is_canceled,month,day,is_repeated_guest,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,1,0,3,1,2,2,0,2,1,0,6,0,0,3.069363,0.013153,-1.67532,-0.979707,-1.285557,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,3.833545,-0.071077,-1.935646,-0.302358,-0.844568
1,1,0,3,1,2,2,0,2,1,0,6,0,0,7.688398,0.013153,-1.67532,-0.979707,-1.285557,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,5.236515,-0.071077,-1.935646,-0.302358,-0.844568
2,1,0,3,1,0,2,0,2,1,0,6,1,0,-0.848046,0.013153,-1.67532,-0.979707,-0.797480,-1.423798,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.576569,-0.302358,-0.844568
3,1,0,2,0,0,0,0,2,1,0,6,1,0,-0.777884,0.013153,-1.67532,-0.979707,-0.797480,-1.423798,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.576569,-0.302358,-0.844568
4,1,0,6,3,0,0,0,2,1,0,6,2,0,-0.766190,0.013153,-1.67532,-0.979707,-0.309402,0.183863,-0.30753,-0.096209,-0.083185,-0.107318,-0.375365,-0.071077,-0.159785,-0.302358,0.354895

In [41]:
X = df.drop(columns = 'is_canceled')
y = df['is_canceled']

In [42]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, stratify= y,test_size = 0.2,random_state=42)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

In [44]:
from sklearn.metrics import confusion_matrix
for model in [LogisticRegression, RandomForestClassifier, XGBClassifier]:
    cls = model()
    cls.fit(X_train, y_train)
    previsao = cls.predict(X_test)

    name = cls.__class__.__name__
    acuracia = (accuracy_score(y_test, previsao)*100).round(2)
    print(f'{name} - Acurácia: {acuracia}%')
    print('='*30)
    clf_report = classification_report(y_test, previsao)
    print(f"Classification Report : \n{clf_report}")
    print()
    print()

LogisticRegression - Acurácia: 79.63%
==============================
Classification Report :
              precision    recall  f1-score   support

           0       0.80      0.95      0.87     12290
           1       0.76      0.40      0.52      4796

    accuracy                           0.80     17086
   macro avg       0.78      0.68      0.70     17086
weighted avg       0.79      0.80      0.77     17086



RandomForestClassifier - Acurácia: 93.04%
==============================
Classification Report :
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     12290
           1       0.97      0.77      0.86      4796

    accuracy                           0.93     17086
   macro avg       0.95      0.88      0.91     17086
weighted avg       0.93      0.93      0.93     17086



XGBClassifier - Acurácia: 99.73%
==============================
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     12290
           1       1.00      0.99      1.00      4796

    accuracy                           1.00     17086
   macro avg       1.00      1.00      1.00     17086
weighted avg       1.00      1.00      1.00     17086